name: NetBan
version: 1.0.3
main: InspectorGadget\NetworkBan\MainHandler
api: 3.0.0
author: InspectorGadget

commands:
  nban:
    permission: nban.command

permissions:
  nban:
    default: op
    description: "NetBan root permission"
    children:
      nban.command:
        description: "Allow you to use NetBan"